#!/usr/bin/env bash
# Function to handle SIGTERM signal
handle_sigterm() {
    echo "I am invincible!!!"
    exit 0
}

# Set up trap to call handle_sigterm function when SIGTERM signal is received
trap 'handle_sigterm' SIGTERM

# Loop indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 2
done

